### ISSUE TITLE
Does it work with Internal repo's?

### ISSUE THREAD

**Issue by leontebbens** [issc29/probot-prevent-public-repos#18]
Hi, Github introduced Internal repo's, does your bot detect changes from "Internal" to "Public" too?
I'd like to enable Internal repo's for my organisation, but still have the protection from your probot.

**Comment by Tioborto** [comment]
Any ETA ?

**Comment by amenocal** [comment]
@leontebbens I was able to test it with Internal repos and had no issues.

**Comment by issc29** [comment]
Should work with internal repos -- let me know if you have any other issues!
