### ISSUE TITLE
Prevent-Public-Repos does not convert newly public repo to private

### ISSUE THREAD

**Issue by sqi-verimatrix** [issc29/probot-prevent-public-repos#3]
Hi Isaac, 

Thanks for the app. I am trying it out to protect my organization's repos. However, I found that the app does not automatically convert a newly created public repo to private. I have created the org-settings/.github/prevent-public-repos.yml file as described, and set monitorOnly: false. 

When creating a public repo, I get an email saying "NOTE: Public Repos are disabled for this organization! Repository was automatically converted to a Private Repo. Please contact an admin to override." However, the repo remains public. Am I missing something? Thanks.

**Comment by mwkeck** [comment]
I have confirmed the same on my side as well. The email notifies that it has flipped the repo but it does not make the change.

**Comment by sqi-verimatrix** [comment]
I eventually figured out the problem. You must enable this option for the script to work: (It is under organization settings --> Member Privileges)
Repository visibility change
Allow members to change repository visibilities for this organization
