### ISSUE TITLE
Upgrade Probot version to support GHE

### ISSUE THREAD

**Issue by issc29** [issc29/probot-prevent-public-repos#6]
Currently, Prevent Public Repos Probot App does uses a version of Probot that is not compatible with GitHub Enterprise.

Recommend: Upgrade version of Probot from `3.0.0` to at least `4.0.0`

From #4

**Comment by kreig303** [comment]
I am also interested in GHE support. I've identified the following before coding (per https://github.com/probot/probot/releases)

1. increment `probot` dependency to `^6.0.0`
2. remove `local-tunnel` dev dependency
3. add `smee-client` dev dependency

Uncertain about other changes yet.

**Comment by kreig303** [comment]
I had a branch on my fork and am now PRing it.

Only additional change was linting fix.

#10

**Comment by kreig303** [comment]
Made some more tweaks... had to fix `.travis.yml` as it was using an inappropriate version of node and causing build failures.

**Comment by issc29** [comment]
Fixed in #10
