### ISSUE TITLE
Not blocking or remediating public repos

### ISSUE THREAD

**Issue by snowake4me** [issc29/probot-prevent-public-repos#7]
Thank you for this useful and relevant probot app!

Unfortunately - it doesn't appear to be working as advertised.  I've pored over the (straightforward) documentation, and Getting Started (4 simple steps) - having completed the following:

- Installed app in my org
- created org-settings repo
- created .github/prevent-public-repos.yml from provided example, and adjusted to 'enforce' mode (e.g. monitorOnly: false, enablePrivateToPublic: true)
- confirmed Settings-> Member Privs -> Repository visibility change -> Allow

Unlike the report in Issue #3  or #5  - I do not receive either the notification, nor is there an Issue being created on the repo.  Totally acknowledging that I must be doing something wrong - but sure can't figure out what it might be!

Thanks in advance.

**Comment by issc29** [comment]
hey @snowake4me,

Looking at some backend logging, I see that there are some YAML errors coming in.

Can you confirm that the YAML syntax for `prevent-public-repos.yml` is correct?
specifically, ensure that `ccList: '@person1 @person2'` has single quotes 😃

**Comment by snowake4me** [comment]
Briliant.  Thanks, Isaac - that was the **exactly** the problem.

Issue #7 was user error - issue closed.
