### ISSUE TITLE
Is it possible to monitor if organization members create a public repo in their personal user account?

### ISSUE THREAD

**Issue by jamesmortensen** [issc29/probot-prevent-public-repos#9]
Is it possible to monitor if organization members create a public repo in their personal user account?

The problem we're facing is users are creating repositories in their personal accounts.  GitHub doesn't show the option to create repositories in the organization for members who do not have permissions.  Instead of showing them a greyed out option that may make them think, the option is hidden.  

Thus, they think this is the only way to create a repository.  If GitHub stopped hiding disabled features, or if your script could also monitor behavior of organization members in their personal profiles, this could help with code security.

**Comment by issc29** [comment]
Hey @jamesmortensen, there isn't a way that I am aware of to monitor when users create a public repo. I would recommend submitting a [support ticket](https://github.com/contact) for this issue so that it can be properly logged for future enhancements!
